src/main/java/com/mwal/test_maven/entities/Offer.java
package com.mwal.test_maven.entities;

import java.util.Date;

import javax.persistence.*;

@Entity
@NamedQueries({
	@NamedQuery(name = "Offer.findAll", query = "SELECT o from Offer o"),
	@NamedQuery(name = "Offer.findById", query = "SELECT o from Offer o WHERE o.id = :id"),
	@NamedQuery(name = "Offer.findByDates", query = "SELECT o from Offer o where o.startDate between :startDate and :endDate")
})
public class Offer {
	
	@Id
	@GeneratedValue
	private long id;
	
	public long getId() {
		return id;
	}
	public void setId(long id) {
		this.id = id;
	}
	private String title;
	private double price;
	private Date startDate;
	@Transient
	private String asText;
	
	public String getAsText() {
		return toString();
	}
	private Date endDate;
	@Lob
	private String shortDescription;
	@Lob
	private String longDescription;
	
	private String photoURL;
	
	public String getPhotoURL() {
		return photoURL;
	}
	public void setPhotoURL(String photoURL) {
		this.photoURL = photoURL;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public double getPrice() {
		return price;
	}
	public void setPrice(double price) {
		this.price = price;
	}
	public Date getStartDate() {
		return startDate;
	}
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}
	public Date getEndDate() {
		return endDate;
	}
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getShortDescription() {
		return shortDescription;
	}
	public void setShortDescription(String shortDescription) {
		this.shortDescription = shortDescription;
	}
	public String getLongDescription() {
		return longDescription;
	}
	public void setLongDescription(String longDescription) {
		this.longDescription = longDescription;
	}
	
	@Override
	public String toString(){
		return getTitle() + " " + getShortDescription();
	}
	

}

src/main/java/com/mwal/test_maven/entities/Photo.java
package com.mwal.test_maven.entities;

import javax.persistence.*;

@Entity
public class Photo {
	@Id
	@GeneratedValue
	private long id;
	
	private String name;
	private String URL;
	
	public Photo(){}
	
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getURL() {
		return URL;
	}

	public void setURL(String uRL) {
		URL = uRL;
	}


}

src/main/java/com/mwal/test_maven/entities/Purchase.java
package com.mwal.test_maven.entities;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;

@Entity
public class Purchase {
	
	@Id
	@GeneratedValue
	private long id;
	
	public Date getTransactionDate() {
		return transactionDate;
	}

	public void setTransactionDate(Date transactionDate) {
		this.transactionDate = transactionDate;
	}

	public Offer getOffer() {
		return offer;
	}

	public void setOffer(Offer offer) {
		this.offer = offer;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	private Date transactionDate;
	
	@ManyToOne
	private Offer offer;
	
	@OneToOne
	private User user;

}

src/main/java/com/mwal/test_maven/entities/User.java
package com.mwal.test_maven.entities;

import java.util.Date;

import javax.persistence.*;

@Entity
public class User {
	
	@Id
	@GeneratedValue
	private long id;
	
	private String userName;

	private String name;
	private String surname;
	private String email;
	private String pesel;
	private Date birthday;
	private String country;
	private boolean isAdmin;
	
	public long getId() {
		return id;
	}
	public void setId(long id) {
		this.id = id;
	}
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getSurname() {
		return surname;
	}
	public void setSurname(String surname) {
		this.surname = surname;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getPesel() {
		return pesel;
	}
	public void setPesel(String pesel) {
		this.pesel = pesel;
	}
	public Date getBirthday() {
		return birthday;
	}
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}
	public String getCountry() {
		return country;
	}
	public void setCountry(String country) {
		this.country = country;
	}
	public boolean isAdmin() {
		return isAdmin;
	}
	public void setAdmin(boolean isAdmin) {
		this.isAdmin = isAdmin;
	}
	
}

src/main/java/com/mwal/test_maven/controller/OfferBean.java
package com.mwal.test_maven.controller;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import java.util.Map;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.faces.event.ActionEvent;
import javax.persistence.EntityManager;

import com.mwal.test_maven.config.DBManager;
import com.mwal.test_maven.entities.Offer;

@ManagedBean
@SessionScoped
public class OfferBean implements Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private Offer offer = new Offer();
	
	private String title;
	private double price;
	private Date startDate;
	private Date endDate;
	private String shortDescription;
	private String longDescription;
	private String photoURL;
	
	
	public String getPhotoURL() {
		return photoURL;
	}

	public void setPhotoURL(String photoURL) {
		this.photoURL = photoURL;
	}

	public String addOffer(){
		offer.setTitle(title);
		System.out.println("Entered addOffer");
		System.out.println("title = " + title);
		offer.setShortDescription(shortDescription);
		offer.setLongDescription(longDescription);
		offer.setPhotoURL(photoURL);
		offer.setStartDate(startDate);
		offer.setEndDate(endDate);
		DBManager manager = DBManager.getManager();
		EntityManager entityMan = manager.createEntityManager();
		entityMan.getTransaction().begin();
		entityMan.persist(offer);
		entityMan.getTransaction().commit();
		this.offer = new Offer();
		return "index?faces-redirect=true";
	}

	private byte[] photo;
	
	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public double getPrice() {
		return price;
	}
	
	public List<Offer> getOfferList(){
		EntityManager manager = DBManager.getManager().createEntityManager();
		List<Offer> list = manager.createNamedQuery("Offer.findAll").getResultList();
		System.out.println("List length: " + list.size());
		manager.close();
		return list;		
	}
	
	public void listener(ActionEvent event){
		FacesContext context = FacesContext.getCurrentInstance();
		ExternalContext exCtx = context.getExternalContext();
		Map<String, String> params = exCtx.getRequestParameterMap();		
		String idString = params.get("id").toString();
		long id = Long.parseLong(idString);
		EntityManager manager = DBManager.getManager().createEntityManager();
		Offer result = (Offer) manager.createNamedQuery("Offer.findById").setParameter("id", id).getResultList().get(0);
		setOffer(result);
	}
	
	public String singleOffer(){
		
		return "offerDetails?faces-redirect=true";
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getShortDescription() {
		return shortDescription;
	}

	public void setShortDescription(String shortDescription) {
		this.shortDescription = shortDescription;
	}

	public String getLongDescription() {
		return longDescription;
	}

	public void setLongDescription(String longDescription) {
		this.longDescription = longDescription;
	}

	public byte[] getPhoto() {
		return photo;
	}

	public void setPhoto(byte[] photo) {
		this.photo = photo;
	}

	public OfferBean(){
		
	}

	public Offer getOffer() {
		return offer;
	}

	public void setOffer(Offer offer) {
		this.offer = offer;
	}
	
	
}

src/main/java/com/mwal/test_maven/controller/UserBean.java
package com.mwal.test_maven.controller;

import java.util.Date;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.persistence.EntityManager;

import com.mwal.test_maven.config.DBManager;
import com.mwal.test_maven.entities.User;

@ManagedBean
@SessionScoped
public class UserBean {
	
	private User user= new User();
	private long id;
	
	private String userName;

	private String name;
	private String surname;
	private String email;
	private String pesel;
	private Date birthday;
	private String country;
	
	
	
	public String addUser(){
		user.setAdmin(false);
		user.setBirthday(birthday);
		user.setCountry(country);
		user.setEmail(email);
		user.setName(name);
		user.setPesel(pesel);
		user.setSurname(surname);
		user.setUserName(userName);
		DBManager manager = DBManager.getManager();
		EntityManager entityMan = manager.createEntityManager();
		entityMan.getTransaction().begin();
		entityMan.persist(user);
		entityMan.getTransaction().commit();
		this.user = new User();
		return "index?faces-redirect=true";
	}
	
	
	public User getUser() {
		return user;
	}
	public void setUser(User user) {
		this.user = user;
	}
	public long getId() {
		return id;
	}
	public void setId(long id) {
		this.id = id;
	}
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getSurname() {
		return surname;
	}
	public void setSurname(String surname) {
		this.surname = surname;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getPesel() {
		return pesel;
	}
	public void setPesel(String pesel) {
		this.pesel = pesel;
	}
	public Date getBirthday() {
		return birthday;
	}
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}
	public String getCountry() {
		return country;
	}
	public void setCountry(String country) {
		this.country = country;
	}
	public boolean isAdmin() {
		return isAdmin;
	}
	public void setAdmin(boolean isAdmin) {
		this.isAdmin = isAdmin;
	}
	private boolean isAdmin;

}

src/main/webapp/create_offer.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
xmlns:ui="http://java.sun.com/jsf/facelets"
xmlns:h="http://java.sun.com/jsf/html"
xmlns:f="http://java.sun.com/jsf/core"
xmlns:t="http://myfaces.apache.org/tomahawk"
xmlns:p="http://primefaces.org/ui">
<h:head>
</h:head>
<h:body>
<h2>Create vacation offer</h2>
<f:view transient="true">
<h:form enctype="multipart/form-data">
<table>
   	<tr><td>Title</td><td><p:inputText id="nazwa" value="#{offerBean.title}" required="true"/></td></tr>
    <tr><td>Short description</td><td><p:inputText id="adres" value="#{offerBean.shortDescription}" required="true"/></td></tr>
    <tr><td>Long description</td><td><p:inputText id="kontakt" value="#{offerBean.longDescription}" required="true"/></td></tr>
    <tr><td>Price</td><td><p:inputText id="opis" value="#{offerBean.price}" required="true"><f:convertNumber/></p:inputText></td></tr>
    <tr><td>Starting date</td><td><p:calendar pattern="dd/MM/yyyy" name="startDate" value="#{offerBean.startDate}"/></td></tr>
    <tr><td>End date</td><td><p:calendar pattern="dd/MM/yyyy" name="endDate" value="#{offerBean.endDate}"/></td></tr>
    <tr><td>Photo</td><td><p:inputText value="#{offerBean.photoURL}"/></td></tr>    
    <tr><td></td><td><p:commandButton id="addButton" action="#{offerBean.addOffer}" value="Add offer"/></td></tr>
</table>
</h:form>
</f:view>
</h:body>
</html>

src/main/webapp/index.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
xmlns:ui="http://java.sun.com/jsf/facelets"
xmlns:h="http://java.sun.com/jsf/html"
xmlns:f="http://java.sun.com/jsf/core">
<head>
        <title>Landing page</title>
    </head>
    <body>
        <h1>Generic Travel Agency #4</h1>
    <h:form>
    <h:commandButton action="create_offer?faces-redirect=true" value="Create an offer" /><br/><br/>
    <h:commandButton action="view_offers?faces-redirect=true" value="View all offers" />
	</h:form>
    </body>

</html>

src/main/webapp/offerDetails.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
xmlns:ui="http://java.sun.com/jsf/facelets"
xmlns:h="http://java.sun.com/jsf/html"
xmlns:f="http://java.sun.com/jsf/core"
xmlns:t="http://myfaces.apache.org/tomahawk"
xmlns:p="http://primefaces.org/ui">
<head>
</head>
<body>
      <h:dataTable value="#{offerBean.offer}" var="offer">
      <h:column>
      	<f:facet name="header">Photo</f:facet>
      	<img src="#{offer.photoURL}" height="300" width="400"/>
      </h:column>
      <h:column>
      	<f:facet name="header">Title</f:facet>
      	<h:outputLabel name="title" value="#{offer.title}"/>
      </h:column>
      <h:column>
      	<f:facet name="header">Description</f:facet>
      	<h:outputLabel name="short" value="#{offer.longDescription}"/>
      </h:column>
      
      <h:column>
      	<f:facet name="header">Price</f:facet>
      	<h:outputLabel name="price" value="#{offer.price}"/>
      </h:column>
      <h:column>
      	<f:facet name="header">Start date</f:facet>
      	<p:outputLabel name="startDate" value="#{offer.startDate}"/>
      </h:column>
      <h:column>
      	<f:facet name="header">End date</f:facet>
      	<p:outputLabel name="endDate" value="#{offer.endDate}"/>
      </h:column>
		<h:column>
			<f:facet name="header">Code</f:facet>
			<p:barcode value="#{offer.asText}" type="qr"/>
		</h:column>

      </h:dataTable>
</body>
</html>

src/main/webapp/register_user.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
xmlns:ui="http://java.sun.com/jsf/facelets"
xmlns:h="http://java.sun.com/jsf/html"
xmlns:f="http://java.sun.com/jsf/core"
xmlns:t="http://myfaces.apache.org/tomahawk"
xmlns:p="http://primefaces.org/ui">
<h:head>

</h:head>
<h:body>
<h1>Register now!</h1>
<h:form>
<table>
	<tr><td><p:outputLabel value="Choose your user name"/></td><td><p:inputText name="userName" value="#{userBean.userName}" required="true"/></td></tr>
	<tr><td><p:outputLabel value="Name"/></td><td><p:inputText name="name" value="#{userBean.name}" required="true"/></td></tr>
	<tr><td><p:outputLabel value="Surname"/></td><td><p:inputText name="surname" value="#{userBean.surname}" required="true"/></td></tr>
	<tr><td><p:outputLabel value="Email"/></td><td><p:inputText name="email" value="#{userBean.email}" required="true"/></td></tr>
	<tr><td><p:outputLabel value="Pesel"/></td><td><p:inputText name="pesel" value="#{userBean.pesel}" required="true"/></td></tr>
	<tr><td><p:outputLabel value="Date of birth"/></td><td><p:calendar name="birthday" value="#{userBean.birthday}" required="true"/></td></tr>
	<tr><td><p:outputLabel value="Country"/></td><td><p:inputText name="country" value="#{userBean.country}" required="true"/></td></tr>
</table>
<p:commandButton id="submit" value="Register" action="#{userBean.addUser}"/>
</h:form>

</h:body>
</html>

src/main/webapp/view_offers.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
 <h:body>   
      <h1>Offer list</h1><br/>
      <h:form enctype="multipart/form-data">
      <h:dataTable value="#{offerBean.offerList}" var="offer">
      <h:column>
      	<f:facet name="header">Title</f:facet>
      	<p:outputLabel name="title" value="#{offer.title}"/>
      </h:column>
      <h:column>
      	<f:facet name="header">Short description</f:facet>
      	<p:outputLabel name="short" value="#{offer.shortDescription}"/>
      </h:column>
      <h:column>
      	<f:facet name="header">Price</f:facet>
      	<p:outputLabel name="price" value="#{offer.price}"/>
      </h:column>
	<h:column>
	<f:facet name="header">View offer</f:facet>
	
	<h:commandLink value="investigate" action="#{offerBean.singleOffer}" actionListener="#{offerBean.listener}"><f:param name="id" value="#{offer.id}"/></h:commandLink>
	
	</h:column>
    </h:dataTable>
      </h:form>
</h:body>
</html>